### ISSUE TITLE
Use Intellisense to cut down on service attribute suggestion list

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/compose-language-service#49]
Rather than having multiple duplicate selections when a user presses ctrl + space eg, `port` short version, `port` long, `build` short, `build` long, `command` for echo or `command` for [echo, hello], I think it would be great to only give the user just one suggestion of that attribute then we put their cursor at a place where the next hit of Space, will bring up the suggestions available, then they can easily scroll through it.  

I'd love most of the behavior to be coalesced into the example below.

User sees just one suggestion for volumes
![image](https://user-images.githubusercontent.com/20650058/140429060-a515983e-0e62-40d7-ba89-fe2f62718038.png)

 Instead of giving them this: 
![image](https://user-images.githubusercontent.com/20650058/140429116-7e7fa6a8-9355-4ea5-8861-de7bece40357.png)

We instead start their cursor right next to the dash
![image](https://user-images.githubusercontent.com/20650058/140429172-c04b49ac-a9f7-45c8-8900-87687e5dc3d8.png)

And then hitting space button does this automaticaly in VS Code 
![image](https://user-images.githubusercontent.com/20650058/140429266-28e16e9f-baf3-41bd-a77d-88d43ad8ab66.png)

Adding this for most if not all of the duplicate selections will help cut down on confusion navigating through the tree of possible completions, and provide the user a better in-line authoring experience.

Right now we have quite a few duplicates in the selection and I can see this list growing over time
![image](https://user-images.githubusercontent.com/20650058/140429466-45b70f37-2ca5-4c25-b7bb-25bc95e24775.png)

**Comment by bwateratmsft** [comment]
I'm not sure I understand what you're asking for. For example, I think it's necessary to show them both options for build. Otherwise how would we know whether to send them to the next line (long form), or not (short form)?

I'd rather just show them what's available up front.
