### ISSUE TITLE
Formatting Documents does not fix indentation

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/compose-language-service#50]
When the compose file looks like this 
![image](https://user-images.githubusercontent.com/20650058/140432396-77e9a32f-fff0-404f-a9da-be941e54cc0b.png)

Pressing shift alt F gives me this

![image](https://user-images.githubusercontent.com/20650058/140432474-3d830eb8-2246-40b1-9cb4-9a8902d06d98.png)

Also, a weird quirky bug, but after I format the document, sometimes when hitting control Z (undo)

I get null on some of the attributes. This may be because I hadn't put a value there yet but I'm not totally sure

**Comment by bwateratmsft** [comment]
All of this is working as designed. In your above example, `dockerfile` is a value in the `context` map. That it's an incorrect compose document is not really relevant to formatting; the job of formatting is to fix spacing on an already-syntactically correct document.

`null` will show up when a map has no values; this is also by-design.

**Comment by ucheNkadiCode** [comment]
![image](https://user-images.githubusercontent.com/20650058/140809352-193cee35-2652-4bbc-b5d9-07a137cc7070.png)

and after Ctrl + Shift + F the document still looks the same

![image](https://user-images.githubusercontent.com/20650058/140809527-f421cf65-a35b-436d-91ca-9a4a23875759.png)

After hovering over the next red line, it is giving a corrective error, but our document formatter doesn't fix this. It was my assumption that this document formatter would be a mix of Prettify with Format. I haven't been able to understand where I can use the Ctrl + Shift + F, because it hasn't really done much besides closing down spaces yet.

**Comment by ucheNkadiCode** [comment]
Is format document not our code? Does it have a different job than what I'm thinking? I was thinking you wrote in some kind of Prettify for Compose files?
