### ISSUE TITLE
More Opinionated spacings on formatting Compose file

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/compose-language-service#51]
In this example, values under an attribute remain spaced out. I think that attribute names can remain spaced such as `ports` and `volumes`, but for the value under `volumes`, it should be thrown right under the `volumes` attribute

**Comment by bwateratmsft** [comment]
Can you describe what you mean? Again, I need to assert that if the user puts in extra whitespace, it is not our place to decide to undo that, even if we think it's weird.

**Comment by ucheNkadiCode** [comment]
Sorry I meant to post a picture. Since the user is opting to press Shift Alt F for the formatting help, I would expect that some spacing could be shifted into the way we suggest. They don't have to use our formatting, but I would hope we format Compose files in a way that people will want to use. So I'm proposing a few improvements here.

![image](https://user-images.githubusercontent.com/20650058/140808150-20e6f206-92eb-48e9-8d4b-ffc9382af2ac.png)

In this case I would want interval /n timeout to become interval-timeout with no spacing. However, I think between higher sections such as build and healthcheck, keeping that spacing would still be great

**Comment by bwateratmsft** [comment]
This is similar to #50 then and is asking for schema-aware formatting, which is just not feasible from a RoI perspective.
