### ISSUE TITLE
Docker compose files do not have autocomplete for "args:"

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/compose-language-service#69]
[According to the compose file documentation, there is an `args` nested under `build`.](https://docs.docker.com/compose/compose-file/compose-file-v3/#args) But when I try to use autocomplete, it's not one of the items in the list.

Expected: autocompletion of `args` when nested under `build`

Actual: `args` does not exist as one of the available autocomplete keys

**Comment by bwateratmsft** [comment]
Dupe of #48.

**Comment by DanKaplanSES** [comment]
Super strange that I didn't find this. I searched for "is:issue build args" before I created this issue. Glad that it's already planned. Thanks.

**Comment by bwateratmsft** [comment]
If you searched in the https://github.com/microsoft/vscode-docker repo that's why it didn't show; we have the language service itself in another repo (here).

**Comment by DanKaplanSES** [comment]
Ahhhhh. Thanks
