### ISSUE TITLE
Docker Compose: Wrapping of Lines >80 characters

### ISSUE THREAD

**Issue by klongmitre** [microsoft/compose-language-service#70]
I'm running into an issue where lines that are longer than 80 characters are automatically wrapped and indented and ignores other editor settings (e.g. wordWrapColumn, minimap.maxColumn, etc.). The only way that I can get the file to stop wrapping when formatted is to set `docker.enableDockerComposeLanguageService` to false, which kind of defeats the purpose. Is there a setting somewhere I'm overlooking that changes the auto-wrapping applied to files set to the `dockercompose` language?

**Comment by bwateratmsft** [comment]
Can you give a screenshot or example?

**Comment by klongmitre** [comment]
Sure...

With `docker.enableDockerComposeLanguageService` set to `false`:
![image](https://user-images.githubusercontent.com/9532930/145081130-76895554-1c64-43a7-ab01-7903f58759e3.png)

With `docker.enableDockerComposeLanguageService` set to `true`:
![image](https://user-images.githubusercontent.com/9532930/145081150-c591a36c-8685-476a-8c94-39c06ee0da04.png)

In both conditions, the configured language setting is:
![image](https://user-images.githubusercontent.com/9532930/145081248-1f1fd99e-f5fc-4983-8de8-5885325da446.png)

**Comment by bwateratmsft** [comment]
Thanks, I'll take a look.

**Comment by klongmitre** [comment]
@bwateratmsft - thanks for looking into this. Is this a configurable parameter?

**Comment by bwateratmsft** [comment]
No unfortunately 😞

Probably the easiest thing to do would be to disable formatting-on-save for Compose documents. In settings.json (user or workspace):
```json
    "[dockercompose]": {
        "editor.formatOnSave": false,
    }
```

This way you can still use the rest of the language service features, without it messing up your formatting. Of course, that means formatting will have to be done manually (<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd>), and when that is done this line wrapping will still happen.
